/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ideveloper;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.*;
import javax.swing.*;
import javax.imageio.ImageIO;

/**
 *
 * @author Higor Felype
 */
public class TelaLogin extends javax.swing.JFrame {
    Usuario User = null;
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFramePrincipal = new javax.swing.JFrame();
        jFoto_FP = new java.awt.Panel();
        jNome_FP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPublic_FP = new javax.swing.JRadioButton();
        jGrupo_FP = new javax.swing.JRadioButton();
        jSair_FP = new javax.swing.JButton();
        jMyGrupo_FP = new javax.swing.JButton();
        jMyPublic_FP = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFrameCadastro = new javax.swing.JFrame();
        jCadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDesc_C = new javax.swing.JTextArea();
        jNome_C = new javax.swing.JTextField();
        jCurso_C = new javax.swing.JTextField();
        jEmail_C = new javax.swing.JTextField();
        jSenha_C = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jFoto_C = new java.awt.Panel();
        jAdd_C = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jVoltar_C = new javax.swing.JButton();
        jFotoFile_C = new javax.swing.JTextField();
        jPerfil = new javax.swing.JFrame();
        jFrameListPublic_FP = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPublic_FP = new javax.swing.JList<>();
        jFrameListGrupo_FP = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListGrupo_FP = new javax.swing.JList<>();
        jFramePublic_User = new javax.swing.JFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListPublic_User = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jTransPublic_User = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jAdicionarPublic_User = new javax.swing.JButton();
        jRemoverPublic_User = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jMyPublic_Desc = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jMyPublic_Painel = new javax.swing.JEditorPane();
        jMyPublic_Tema = new javax.swing.JTextField();
        jReprovacoes = new javax.swing.JTextField();
        jAprovacoes = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jFrameGrupo_User = new javax.swing.JFrame();
        jVoltarPublic_User = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListGrupo_User = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jRemover_Grupo_User = new javax.swing.JButton();
        jVerInteresses_User = new javax.swing.JButton();
        jMyGrupo_Tema = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jMyGrupo_Desc = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jMyGrupo_LimitInt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jFrameAlterarPublic = new javax.swing.JFrame();
        jFrameOlharInteressados = new javax.swing.JFrame();
        jFramePublic_UserAdd = new javax.swing.JFrame();
        jAddPublic_Botao = new javax.swing.JToggleButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jAddPublic_Desc = new javax.swing.JTextArea();
        jAddPublic_Painel = new java.awt.Panel();
        jLabel17 = new javax.swing.JLabel();
        jAddPublic_Tema = new javax.swing.JTextField();
        jAddPublic_Add = new javax.swing.JButton();
        jAddPublic_File = new javax.swing.JTextField();
        jFramePublic_UserTrans = new javax.swing.JFrame();
        jLabel18 = new javax.swing.JLabel();
        jQt_Part = new javax.swing.JSpinner();
        jTransPublic_Confirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jEntrar = new javax.swing.JButton();
        jSenha = new javax.swing.JPasswordField();
        jCadastro = new javax.swing.JButton();
        jEmail = new javax.swing.JTextField();

        jFramePrincipal.setBounds(new java.awt.Rectangle(0, 0, 620, 445));

        jFoto_FP.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jFoto_FPLayout = new javax.swing.GroupLayout(jFoto_FP);
        jFoto_FP.setLayout(jFoto_FPLayout);
        jFoto_FPLayout.setHorizontalGroup(
            jFoto_FPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jFoto_FPLayout.setVerticalGroup(
            jFoto_FPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        jLabel3.setText("Meus/Minhas:");

        jLabel4.setText("TimeLine");

        buttonGroup2.add(jPublic_FP);
        jPublic_FP.setText("Publicações");
        jPublic_FP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPublic_FPMouseClicked(evt);
            }
        });

        buttonGroup2.add(jGrupo_FP);
        jGrupo_FP.setText("Grupos");
        jGrupo_FP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGrupo_FPMouseClicked(evt);
            }
        });

        jSair_FP.setText("sair");
        jSair_FP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSair_FPMouseClicked(evt);
            }
        });

        jMyGrupo_FP.setText("Grupos");
        jMyGrupo_FP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyGrupo_FPActionPerformed(evt);
            }
        });

        jMyPublic_FP.setText("Publicações");
        jMyPublic_FP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyPublic_FPActionPerformed(evt);
            }
        });

        jButton1.setText("Edite");

        javax.swing.GroupLayout jFramePrincipalLayout = new javax.swing.GroupLayout(jFramePrincipal.getContentPane());
        jFramePrincipal.getContentPane().setLayout(jFramePrincipalLayout);
        jFramePrincipalLayout.setHorizontalGroup(
            jFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFramePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jFramePrincipalLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFramePrincipalLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMyGrupo_FP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMyPublic_FP)))
                            .addComponent(jLabel3)))
                    .addComponent(jNome_FP, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFoto_FP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(122, 122, 122)
                .addGroup(jFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFramePrincipalLayout.createSequentialGroup()
                        .addGroup(jFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFramePrincipalLayout.createSequentialGroup()
                                .addComponent(jGrupo_FP)
                                .addGap(22, 22, 22))
                            .addComponent(jPublic_FP, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFramePrincipalLayout.createSequentialGroup()
                        .addComponent(jSair_FP)
                        .addGap(22, 22, 22))))
        );
        jFramePrincipalLayout.setVerticalGroup(
            jFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFramePrincipalLayout.createSequentialGroup()
                        .addGroup(jFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSair_FP)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addComponent(jPublic_FP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGrupo_FP))
                    .addGroup(jFramePrincipalLayout.createSequentialGroup()
                        .addComponent(jNome_FP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFoto_FP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMyPublic_FP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMyGrupo_FP)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jFrameCadastro.setBounds(new java.awt.Rectangle(0, 0, 534, 393));

        jCadastrar.setText("Cadastrar");
        jCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCadastrarMouseClicked(evt);
            }
        });

        jLabel5.setText("Nome");

        jLabel6.setText("Curso");

        jLabel7.setText("E-mail");

        jLabel8.setText("Senha");

        jDesc_C.setColumns(20);
        jDesc_C.setRows(5);
        jScrollPane2.setViewportView(jDesc_C);

        jLabel9.setText("Descrição Pessoal");

        jFoto_C.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jFoto_CLayout = new javax.swing.GroupLayout(jFoto_C);
        jFoto_C.setLayout(jFoto_CLayout);
        jFoto_CLayout.setHorizontalGroup(
            jFoto_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        jFoto_CLayout.setVerticalGroup(
            jFoto_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        jAdd_C.setText("Adicionar");
        jAdd_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAdd_CMouseClicked(evt);
            }
        });

        jLabel10.setText("Cadastro");

        jVoltar_C.setText("Voltar");
        jVoltar_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVoltar_CMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jFrameCadastroLayout = new javax.swing.GroupLayout(jFrameCadastro.getContentPane());
        jFrameCadastro.getContentPane().setLayout(jFrameCadastroLayout);
        jFrameCadastroLayout.setHorizontalGroup(
            jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameCadastroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameCadastroLayout.createSequentialGroup()
                        .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrameCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(jFrameCadastroLayout.createSequentialGroup()
                        .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCurso_C)
                            .addComponent(jEmail_C, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(jNome_C)
                            .addComponent(jSenha_C, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jFrameCadastroLayout.createSequentialGroup()
                                .addComponent(jFoto_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAdd_C))
                            .addComponent(jFotoFile_C))
                        .addContainerGap(63, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameCadastroLayout.createSequentialGroup()
                        .addComponent(jCadastrar)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(168, 168, 168)
                        .addComponent(jVoltar_C))))
        );
        jFrameCadastroLayout.setVerticalGroup(
            jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameCadastroLayout.createSequentialGroup()
                .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jVoltar_C))
                .addGap(13, 13, 13)
                .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameCadastroLayout.createSequentialGroup()
                        .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jNome_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jCurso_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jEmail_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jSenha_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jFoto_C, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdd_C, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFotoFile_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCadastrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPerfilLayout = new javax.swing.GroupLayout(jPerfil.getContentPane());
        jPerfil.getContentPane().setLayout(jPerfilLayout);
        jPerfilLayout.setHorizontalGroup(
            jPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPerfilLayout.setVerticalGroup(
            jPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFrameListPublic_FP.setSize(new java.awt.Dimension(300, 425));

        jListPublic_FP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPublic_FPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListPublic_FP);

        javax.swing.GroupLayout jFrameListPublic_FPLayout = new javax.swing.GroupLayout(jFrameListPublic_FP.getContentPane());
        jFrameListPublic_FP.getContentPane().setLayout(jFrameListPublic_FPLayout);
        jFrameListPublic_FPLayout.setHorizontalGroup(
            jFrameListPublic_FPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        jFrameListPublic_FPLayout.setVerticalGroup(
            jFrameListPublic_FPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jListGrupo_FP);

        javax.swing.GroupLayout jFrameListGrupo_FPLayout = new javax.swing.GroupLayout(jFrameListGrupo_FP.getContentPane());
        jFrameListGrupo_FP.getContentPane().setLayout(jFrameListGrupo_FPLayout);
        jFrameListGrupo_FPLayout.setHorizontalGroup(
            jFrameListGrupo_FPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jFrameListGrupo_FPLayout.setVerticalGroup(
            jFrameListGrupo_FPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        jListPublic_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPublic_UserMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jListPublic_User);

        jLabel12.setText("Minhas Publicações");

        jTransPublic_User.setText("Transformar em Grupo");
        jTransPublic_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTransPublic_UserMouseClicked(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jAdicionarPublic_User.setText("Adicionar Publicação");
        jAdicionarPublic_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAdicionarPublic_UserMouseClicked(evt);
            }
        });

        jRemoverPublic_User.setText("Remover Publicação");
        jRemoverPublic_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRemoverPublic_UserMouseClicked(evt);
            }
        });

        jMyPublic_Desc.setColumns(20);
        jMyPublic_Desc.setRows(5);
        jScrollPane6.setViewportView(jMyPublic_Desc);

        jScrollPane7.setViewportView(jMyPublic_Painel);

        jLabel13.setText("Aprovações");

        jLabel14.setText("Reprovações");

        javax.swing.GroupLayout jFramePublic_UserLayout = new javax.swing.GroupLayout(jFramePublic_User.getContentPane());
        jFramePublic_User.getContentPane().setLayout(jFramePublic_UserLayout);
        jFramePublic_UserLayout.setHorizontalGroup(
            jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePublic_UserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFramePublic_UserLayout.createSequentialGroup()
                        .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jFramePublic_UserLayout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jMyPublic_Tema, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                                    .addGroup(jFramePublic_UserLayout.createSequentialGroup()
                                        .addComponent(jAprovacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(jFramePublic_UserLayout.createSequentialGroup()
                                        .addComponent(jReprovacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTransPublic_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAdicionarPublic_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRemoverPublic_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jFramePublic_UserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(174, 174, 174)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jFramePublic_UserLayout.setVerticalGroup(
            jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePublic_UserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jFramePublic_UserLayout.createSequentialGroup()
                        .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRemoverPublic_User)
                            .addComponent(jMyPublic_Tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFramePublic_UserLayout.createSequentialGroup()
                                .addComponent(jAdicionarPublic_User)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTransPublic_User))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                    .addComponent(jScrollPane7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAprovacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFramePublic_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReprovacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jVoltarPublic_User.setText("Voltar");
        jVoltarPublic_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVoltarPublic_UserMouseClicked(evt);
            }
        });

        jListGrupo_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListGrupo_UserMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jListGrupo_User);

        jLabel11.setText("Meus Grupos");

        jRemover_Grupo_User.setText("Remover Grupo");
        jRemover_Grupo_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRemover_Grupo_UserMouseClicked(evt);
            }
        });

        jVerInteresses_User.setText("Ver Interessados");
        jVerInteresses_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVerInteresses_UserActionPerformed(evt);
            }
        });

        jMyGrupo_Desc.setColumns(20);
        jMyGrupo_Desc.setRows(5);
        jScrollPane8.setViewportView(jMyGrupo_Desc);

        jLabel15.setText("/");

        jLabel16.setText("Limite de Integrantes");

        javax.swing.GroupLayout jFrameGrupo_UserLayout = new javax.swing.GroupLayout(jFrameGrupo_User.getContentPane());
        jFrameGrupo_User.getContentPane().setLayout(jFrameGrupo_UserLayout);
        jFrameGrupo_UserLayout.setHorizontalGroup(
            jFrameGrupo_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameGrupo_UserLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jVoltarPublic_User)
                .addContainerGap())
            .addGroup(jFrameGrupo_UserLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jRemover_Grupo_User, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameGrupo_UserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFrameGrupo_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameGrupo_UserLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(jFrameGrupo_UserLayout.createSequentialGroup()
                        .addGroup(jFrameGrupo_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jMyGrupo_Tema)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                        .addGroup(jFrameGrupo_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrameGrupo_UserLayout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(jVerInteresses_User))
                            .addGroup(jFrameGrupo_UserLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jMyGrupo_LimitInt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrameGrupo_UserLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel16)))
                        .addContainerGap())))
        );
        jFrameGrupo_UserLayout.setVerticalGroup(
            jFrameGrupo_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameGrupo_UserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameGrupo_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVoltarPublic_User)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jRemover_Grupo_User)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameGrupo_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVerInteresses_User)
                    .addComponent(jMyGrupo_Tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameGrupo_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameGrupo_UserLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrameGrupo_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jMyGrupo_LimitInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameAlterarPublicLayout = new javax.swing.GroupLayout(jFrameAlterarPublic.getContentPane());
        jFrameAlterarPublic.getContentPane().setLayout(jFrameAlterarPublicLayout);
        jFrameAlterarPublicLayout.setHorizontalGroup(
            jFrameAlterarPublicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrameAlterarPublicLayout.setVerticalGroup(
            jFrameAlterarPublicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrameOlharInteressadosLayout = new javax.swing.GroupLayout(jFrameOlharInteressados.getContentPane());
        jFrameOlharInteressados.getContentPane().setLayout(jFrameOlharInteressadosLayout);
        jFrameOlharInteressadosLayout.setHorizontalGroup(
            jFrameOlharInteressadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrameOlharInteressadosLayout.setVerticalGroup(
            jFrameOlharInteressadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jAddPublic_Botao.setText("Confirmar");
        jAddPublic_Botao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddPublic_BotaoMouseClicked(evt);
            }
        });

        jAddPublic_Desc.setColumns(20);
        jAddPublic_Desc.setRows(5);
        jScrollPane9.setViewportView(jAddPublic_Desc);

        javax.swing.GroupLayout jAddPublic_PainelLayout = new javax.swing.GroupLayout(jAddPublic_Painel);
        jAddPublic_Painel.setLayout(jAddPublic_PainelLayout);
        jAddPublic_PainelLayout.setHorizontalGroup(
            jAddPublic_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jAddPublic_PainelLayout.setVerticalGroup(
            jAddPublic_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel17.setText("Publicação");

        jAddPublic_Add.setText("Adicionar");
        jAddPublic_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddPublic_AddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jFramePublic_UserAddLayout = new javax.swing.GroupLayout(jFramePublic_UserAdd.getContentPane());
        jFramePublic_UserAdd.getContentPane().setLayout(jFramePublic_UserAddLayout);
        jFramePublic_UserAddLayout.setHorizontalGroup(
            jFramePublic_UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePublic_UserAddLayout.createSequentialGroup()
                .addGroup(jFramePublic_UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFramePublic_UserAddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jFramePublic_UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAddPublic_Tema)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                        .addGroup(jFramePublic_UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFramePublic_UserAddLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jFramePublic_UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAddPublic_Painel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAddPublic_Botao, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jFramePublic_UserAddLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jAddPublic_Add))))
                    .addGroup(jFramePublic_UserAddLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jFramePublic_UserAddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jAddPublic_File)))
                .addContainerGap())
        );
        jFramePublic_UserAddLayout.setVerticalGroup(
            jFramePublic_UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePublic_UserAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(13, 13, 13)
                .addGroup(jFramePublic_UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddPublic_Tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddPublic_Add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFramePublic_UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAddPublic_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAddPublic_File, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAddPublic_Botao)
                .addContainerGap())
        );

        jLabel18.setText("Defina o limite de integrantes no Grupo a ser criado:");

        jTransPublic_Confirmar.setText("Confirmar");
        jTransPublic_Confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTransPublic_ConfirmarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jFramePublic_UserTransLayout = new javax.swing.GroupLayout(jFramePublic_UserTrans.getContentPane());
        jFramePublic_UserTrans.getContentPane().setLayout(jFramePublic_UserTransLayout);
        jFramePublic_UserTransLayout.setHorizontalGroup(
            jFramePublic_UserTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePublic_UserTransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jQt_Part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFramePublic_UserTransLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTransPublic_Confirmar)
                .addContainerGap())
        );
        jFramePublic_UserTransLayout.setVerticalGroup(
            jFramePublic_UserTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePublic_UserTransLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jFramePublic_UserTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jQt_Part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jTransPublic_Confirmar)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("e-mail");

        jLabel2.setText("senha");

        jEntrar.setText("Entrar");
        jEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEntrarMouseClicked(evt);
            }
        });

        jCadastro.setText("Cadastrar-se");
        jCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCadastroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEmail)))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCadastro)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEntrar)
                    .addComponent(jCadastro))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEntrarMouseClicked
        Usuario U = Cliente_.entrar(jEmail.getText(), new String(jSenha.getPassword()));
        if (U != null) {
            jFramePrincipal.setVisible(true);
            jNome_FP.setText(U.getPerfil().getNome());
 
            if (U.getPerfil().getFoto() != null) {
                File F = U.getPerfil().getFoto();
                BufferedImage img;
                try {
                    img = ImageIO.read(F);
                    Graphics g = img.getGraphics();
                    this.jFoto_FP.getGraphics().clearRect(0, 0, jFoto_FP.
                            getWidth(), jFoto_FP.getHeight());
                    this.jFoto_FP.getGraphics().drawImage(img, 0, 0, new JLayeredPane());
                } catch (IOException E) {
                    System.out.println("Erro: entrada de foto inválida!");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Login/Senha inválidos!");
        }
    }//GEN-LAST:event_jEntrarMouseClicked

    private void jSair_FPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSair_FPMouseClicked
        jFramePrincipal.setVisible(false);
    }//GEN-LAST:event_jSair_FPMouseClicked

    private void jCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCadastroMouseClicked
        jFrameCadastro.setVisible(true);
    }//GEN-LAST:event_jCadastroMouseClicked

    private void jVoltar_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVoltar_CMouseClicked
        jVoltar_C.setVisible(false);
    }//GEN-LAST:event_jVoltar_CMouseClicked

    private void jCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCadastrarMouseClicked
        Usuario U = new Usuario(jEmail_C.getText(), new String(jSenha_C.getPassword()));
        U.editPerfil(jDesc_C.getText(), jNome_C.getText(), jCurso_C.getText(), new File(jFotoFile_C.getText()));
        if (Cliente_.Cadastrar(U)) {
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Já existe um usuario no sistema!");
        }
    }//GEN-LAST:event_jCadastrarMouseClicked

    private void jAdd_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdd_CMouseClicked
        JFileChooser filechooser = new JFileChooser();
        int retorno = filechooser.showOpenDialog(null);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            File F = filechooser.getSelectedFile();
            jFotoFile_C.setText(F.toString());

            BufferedImage img;
            try {
                img = ImageIO.read(F);
                Graphics g = img.getGraphics();
                this.jFoto_C.getGraphics().clearRect(0, 0, jFoto_C.getWidth(), jFoto_C.getHeight());
                this.jFoto_C.getGraphics().drawImage(img, 0, 0, new JLayeredPane());
            } catch (IOException E) {
                System.out.println("Erro: sistema de entrada em falha");
            }
        }
    }//GEN-LAST:event_jAdd_CMouseClicked

    private void jPublic_FPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPublic_FPMouseClicked
        jFrameListGrupo_FP.setVisible(false);
        jFrameListPublic_FP.setVisible(true);
    }//GEN-LAST:event_jPublic_FPMouseClicked

    private void jGrupo_FPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGrupo_FPMouseClicked
        jFrameListGrupo_FP.setVisible(true);
        jFrameListPublic_FP.setVisible(false);
    }//GEN-LAST:event_jGrupo_FPMouseClicked

    private void jListPublic_FPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPublic_FPMouseClicked

    }//GEN-LAST:event_jListPublic_FPMouseClicked

    private void jMyPublic_FPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyPublic_FPActionPerformed
        DefaultListModel<Publicacao> jmodel = (DefaultListModel<Publicacao>) jListPublic_User.getModel();
        for (int i = 0; i < this.User.getPublicacoes().size(); i++) {
            if (!jmodel.contains(this.User.getPublicacoes().get(i))) {
                jmodel.addElement(this.User.getPublicacoes().get(i));
            }
        }
        jFramePublic_User.setVisible(true);
        jFramePrincipal.setVisible(false);
    }//GEN-LAST:event_jMyPublic_FPActionPerformed

    private void jMyGrupo_FPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyGrupo_FPActionPerformed
        DefaultListModel<Grupo> jmodel = (DefaultListModel<Grupo>) jListGrupo_User.getModel();
        for (int i = 0; i < this.User.getGrupos().size(); i++) {
            if (!jmodel.contains(this.User.getGrupos().get(i))) {
                jmodel.addElement(this.User.getGrupos().get(i));
            }
        }
        jFrameGrupo_User.setVisible(true);
        jFramePrincipal.setVisible(false);
    }//GEN-LAST:event_jMyGrupo_FPActionPerformed

    private void jVoltarPublic_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVoltarPublic_UserMouseClicked
        jFrameGrupo_User.setVisible(false);
        jFramePrincipal.setVisible(true);
    }//GEN-LAST:event_jVoltarPublic_UserMouseClicked

    private void jRemover_Grupo_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRemover_Grupo_UserMouseClicked
        DefaultListModel<Grupo> model = (DefaultListModel<Grupo>) this.jListGrupo_User.getModel();
        model.remove(jListGrupo_User.getSelectedIndex());
        this.User.getGrupos().remove(model.get(jListGrupo_User.getSelectedIndex()));
    }//GEN-LAST:event_jRemover_Grupo_UserMouseClicked

    private void jVerInteresses_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVerInteresses_UserActionPerformed
        //DefaultListModel<Usuario> model = (DefaultListModel<Usuario>) this.j.getModel() ;
        jFrameOlharInteressados.setVisible(true);
        jFrameGrupo_User.setVisible(false);
    }//GEN-LAST:event_jVerInteresses_UserActionPerformed

    private void jListPublic_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPublic_UserMouseClicked
        DefaultListModel<Publicacao> jmodel = (DefaultListModel<Publicacao>) jListPublic_User.getModel();
        Publicacao P = jmodel.get(jListPublic_User.getSelectedIndex());
        jMyPublic_Desc.setText(P.getDescricao());
        jMyPublic_Tema.setText(P.getTema());
        File F = P.getFoto();
        BufferedImage img;
        try {
            img = ImageIO.read(F);
            Graphics g = img.getGraphics();
            this.jMyPublic_Painel.getGraphics().clearRect(0, 0, jMyPublic_Painel.
                    getWidth(), jMyPublic_Painel.getHeight());
            this.jMyPublic_Painel.getGraphics().drawImage(img, 0, 0, new JLayeredPane());
        } catch (IOException E) {
            System.out.println("sistema de entrada com erro");
        }
        jAprovacoes.setText(" "+ P.getAprovacoes());
        jReprovacoes.setText(" "+ P.getReprovacoes());
    }//GEN-LAST:event_jListPublic_UserMouseClicked

    private void jListGrupo_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListGrupo_UserMouseClicked
        DefaultListModel<Grupo> model = (DefaultListModel<Grupo>) this.jListGrupo_User.getModel();
        Grupo G = model.get(jListGrupo_User.getSelectedIndex());
        jMyGrupo_Desc.setText(G.getPublicacao().getDescricao());
        jMyGrupo_Tema.setText(G.getPublicacao().getTema());
        jMyGrupo_LimitInt.setText("" + G.getLimitIntegrantes());
    }//GEN-LAST:event_jListGrupo_UserMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jFramePublic_User.setVisible(false);
        jFramePrincipal.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jRemoverPublic_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRemoverPublic_UserMouseClicked
        DefaultListModel<Publicacao> model = (DefaultListModel<Publicacao>) this.jListPublic_User.getModel();
        model.remove(jListPublic_User.getSelectedIndex());
        this.User.getPublicacoes().remove(jListPublic_User.getSelectedIndex());
    }//GEN-LAST:event_jRemoverPublic_UserMouseClicked

    private void jAdicionarPublic_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdicionarPublic_UserMouseClicked
        jFramePublic_UserAdd.setVisible(true);
    }//GEN-LAST:event_jAdicionarPublic_UserMouseClicked

    private void jAddPublic_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddPublic_AddMouseClicked
        JFileChooser filechooser = new JFileChooser();
        int retorno = filechooser.showOpenDialog(null);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            File F = filechooser.getSelectedFile();
            jAddPublic_File.setText(F.toString());

            BufferedImage img;
            try {
                img = ImageIO.read(F);
                Graphics g = img.getGraphics();
                this.jAddPublic_Painel.getGraphics().clearRect(0, 0, jAddPublic_Painel.getWidth(), jAddPublic_Painel.getHeight());
                this.jAddPublic_Painel.getGraphics().drawImage(img, 0, 0, new JLayeredPane());
            } catch (IOException E) {
                System.out.println("Erro: sistema de entrada em falha");
            }
        }
    }//GEN-LAST:event_jAddPublic_AddMouseClicked

    private void jAddPublic_BotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddPublic_BotaoMouseClicked
        Publicacao P = new Publicacao(jAddPublic_Tema.getText(), jAddPublic_Desc.getText(), new File(jAddPublic_File.getText()));
        this.User.addPublicacao(P);
    }//GEN-LAST:event_jAddPublic_BotaoMouseClicked

    private void jTransPublic_ConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTransPublic_ConfirmarMouseClicked
        DefaultListModel<Publicacao> model = (DefaultListModel<Publicacao>) this.jListPublic_User.getModel();
        Grupo G = new Grupo(model.get(jListPublic_User.getSelectedIndex()), Integer.parseInt(jQt_Part.getValue().toString()));
        this.User.getGrupos().add(G);
        model.remove(jListPublic_User.getSelectedIndex());
    }//GEN-LAST:event_jTransPublic_ConfirmarMouseClicked

    private void jTransPublic_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTransPublic_UserMouseClicked
        
    }//GEN-LAST:event_jTransPublic_UserMouseClicked
    
    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jAddPublic_Add;
    private javax.swing.JToggleButton jAddPublic_Botao;
    private javax.swing.JTextArea jAddPublic_Desc;
    private javax.swing.JTextField jAddPublic_File;
    private java.awt.Panel jAddPublic_Painel;
    private javax.swing.JTextField jAddPublic_Tema;
    private javax.swing.JButton jAdd_C;
    private javax.swing.JButton jAdicionarPublic_User;
    private javax.swing.JTextField jAprovacoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jCadastrar;
    private javax.swing.JButton jCadastro;
    private javax.swing.JTextField jCurso_C;
    private javax.swing.JTextArea jDesc_C;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jEmail_C;
    private javax.swing.JButton jEntrar;
    private javax.swing.JTextField jFotoFile_C;
    private java.awt.Panel jFoto_C;
    private java.awt.Panel jFoto_FP;
    private javax.swing.JFrame jFrameAlterarPublic;
    private javax.swing.JFrame jFrameCadastro;
    private javax.swing.JFrame jFrameGrupo_User;
    private javax.swing.JFrame jFrameListGrupo_FP;
    private javax.swing.JFrame jFrameListPublic_FP;
    private javax.swing.JFrame jFrameOlharInteressados;
    private javax.swing.JFrame jFramePrincipal;
    private javax.swing.JFrame jFramePublic_User;
    private javax.swing.JFrame jFramePublic_UserAdd;
    private javax.swing.JFrame jFramePublic_UserTrans;
    private javax.swing.JRadioButton jGrupo_FP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<Grupo> jListGrupo_FP;
    private javax.swing.JList<Grupo> jListGrupo_User;
    private javax.swing.JList<Publicacao> jListPublic_FP;
    private javax.swing.JList<Publicacao> jListPublic_User;
    private javax.swing.JTextArea jMyGrupo_Desc;
    private javax.swing.JButton jMyGrupo_FP;
    private javax.swing.JTextField jMyGrupo_LimitInt;
    private javax.swing.JTextField jMyGrupo_Tema;
    private javax.swing.JTextArea jMyPublic_Desc;
    private javax.swing.JButton jMyPublic_FP;
    private javax.swing.JEditorPane jMyPublic_Painel;
    private javax.swing.JTextField jMyPublic_Tema;
    private javax.swing.JTextField jNome_C;
    private javax.swing.JTextField jNome_FP;
    private javax.swing.JFrame jPerfil;
    private javax.swing.JRadioButton jPublic_FP;
    private javax.swing.JSpinner jQt_Part;
    private javax.swing.JButton jRemoverPublic_User;
    private javax.swing.JButton jRemover_Grupo_User;
    private javax.swing.JTextField jReprovacoes;
    private javax.swing.JButton jSair_FP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPasswordField jSenha;
    private javax.swing.JPasswordField jSenha_C;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton jTransPublic_Confirmar;
    private javax.swing.JButton jTransPublic_User;
    private javax.swing.JButton jVerInteresses_User;
    private javax.swing.JButton jVoltarPublic_User;
    private javax.swing.JButton jVoltar_C;
    // End of variables declaration//GEN-END:variables

}
